name: Bundle CI
on:
  push:
    branches: ['2.x']
  pull_request:
  schedule:
    - cron: '0 */12 * * *'

jobs:
  tests:
    runs-on: ubuntu-latest
    permissions: {}

    strategy:
      fail-fast: false
      matrix:
        php-version: ['8.1', '8.2', '8.3', '8.4']
        dependency-version: [ 'highest' ]
        symfony-version: [ '' ]
        minimum-stability: ['stable']
        include:
          # dev packages (probably not needed to have multiple such jobs)
          -   minimum-stability: 'dev'
              php-version: '8.5'
          # lowest deps
          -   php-version: '8.1'
              dependency-version: 'lowest'
          # LTS version of Symfony
          -   php-version: '8.1'
              symfony-version: '6.4.*'
          # Explicit Symfony versions
          -  php-version: '8.1'
             symfony-version: '5.4.*'
          -  php-version: '8.2'
             symfony-version: '7.3.*'
          -  php-version: '8.4'
             symfony-version: '8.0.*'

    env:
      SYMFONY_REQUIRE: ${{ matrix.symfony-version || '>=5.4' }}

    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
        with:
          persist-credentials: false

      - name: Setup PHP
        uses: shivammathur/setup-php@083d5237d9340d541bf95e2a6eceaf3529b85892
        with:
            coverage: "none"
            php-version: "${{ matrix.php-version }}"
            tools: flex

      - name: Allow Flex Plugin
        run: composer global config --no-plugins allow-plugins.symfony/flex true

      - name: Configure Composer minimum stability
        run: composer config minimum-stability ${{ matrix.minimum-stability || 'stable' }} --ansi

      - name: "Composer install"
        uses: ramsey/composer-install@26d8a556604053a9612623447203a691f406fbe6
        with:
            dependency-versions: "${{ matrix.dependency-version }}"
            composer-options: "--prefer-dist --no-progress"
            custom-cache-suffix: "min-stability=${{ matrix.minimum-stability || 'stable' }}"

      - name: Run tests
        run: ./vendor/bin/simple-phpunit
