name: Fabbot

on:
  pull_request:

permissions:
  contents: read

jobs:
  call-fabbot:
    name: Fabbot
    uses: symfony-tools/fabbot/.github/workflows/fabbot.yml@main # zizmor: ignore[unpinned-uses]
    with:
      package: WebpackEncoreBundle
      check_license: true
