on: [pull_request]
name: Static analysis

jobs:
  phpstan:
    name: PHPStan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: 'Cache Dagger'
        uses: actions/cache@v4
        with:
          path: |
            ~/.config/dagger
            ~/.cache/dagger
          key: ${{ runner.os }}-dagger-${{ hashFiles('dagger.json', '.dagger/src/**') }}
          restore-keys: ${{ runner.os }}-dagger-

      - name: 'Run PHPStan'
        uses: dagger/dagger-for-github@8.0.0
        with:
          version: 'latest'
          call: 'static phpstan'
        env:
          DAGGER_NO_NAG: '1'

  php-cs-fixer:
    name: PHP-CS-Fixer
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: 'Cache Dagger'
        uses: actions/cache@v4
        with:
          path: |
            ~/.config/dagger
            ~/.cache/dagger
          key: ${{ runner.os }}-dagger-${{ hashFiles('dagger.json', '.dagger/src/**') }}
          restore-keys: ${{ runner.os }}-dagger-

      - name: 'Run test suite'
        uses: dagger/dagger-for-github@8.0.0
        with:
          version: 'latest'
          call: 'static cs'
        env:
          DAGGER_NO_NAG: '1'

  psalm:
    name: Psalm
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: 'Cache Dagger'
        uses: actions/cache@v4
        with:
          path: |
            ~/.config/dagger
            ~/.cache/dagger
          key: ${{ runner.os }}-dagger-${{ hashFiles('dagger.json', '.dagger/src/**') }}
          restore-keys: ${{ runner.os }}-dagger-

      - name: 'Run test suite'
        uses: dagger/dagger-for-github@8.0.0
        with:
          version: 'latest'
          call: 'static psalm'
        env:
          DAGGER_NO_NAG: '1'

  composer-normalize:
    name: Composer Normalize
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: 'Cache Dagger'
        uses: actions/cache@v4
        with:
          path: |
            ~/.config/dagger
            ~/.cache/dagger
          key: ${{ runner.os }}-dagger-${{ hashFiles('dagger.json', '.dagger/src/**') }}
          restore-keys: ${{ runner.os }}-dagger-

      - name: 'Run test suite'
        uses: dagger/dagger-for-github@8.0.0
        with:
          version: 'latest'
          call: 'static composer-normalize'
        env:
          DAGGER_NO_NAG: '1'
