on: [pull_request]
name: Static analysis

jobs:
  phpstan:
    name: PHPStan
    runs-on: ubuntu-latest
    permissions: {}

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Setup PHP
        uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # 2.37.2
        with:
          php-version: 8.1
          coverage: none
          tools: cs2pr

      - name: Download dependencies
        uses: ramsey/composer-install@65e4f84970763564f46a70b8a54b90d033b3bdda # 4.0.0

      - name: Install PHPStan
        uses: ramsey/composer-install@65e4f84970763564f46a70b8a54b90d033b3bdda # 4.0.0
        with:
          composer-options: "--working-dir=tools/phpstan"

      - name: PHPStan
        run: tools/phpstan/vendor/bin/phpstan analyze --no-progress --error-format=checkstyle | cs2pr

  psalm:
    name: Psalm
    runs-on: ubuntu-latest
    permissions: {}

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Setup PHP
        uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # 2.37.2
        with:
          php-version: 8.1
          coverage: none
          tools: vimeo/psalm:4.11.2

      - name: Download dependencies
        uses: ramsey/composer-install@65e4f84970763564f46a70b8a54b90d033b3bdda # 4.0.0

      - name: Install psalm
        uses: ramsey/composer-install@65e4f84970763564f46a70b8a54b90d033b3bdda # 4.0.0
        with:
          composer-options: "--working-dir=tools/psalm"

      - name: Psalm
        run: tools/psalm/vendor/bin/psalm --no-progress

  composer-normalize:
    name: Composer Normalize
    runs-on: ubuntu-latest
    permissions: {}

    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # 2.37.2
        with:
          php-version: 8.1
          coverage: none
          tools: composer-normalize

      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Normalize
        run: composer-normalize --dry-run
